import { defineStore } from 'pinia'

export const useSettingStore = defineStore('setting', {
    state: () => ({
        domainList: [],
        settings: {
            register: 0,
            receive: 0,
            title: '',
            manyEmail: 0,
            addEmail: 0,
            autoRefresh: 0,
            addEmailVerify: 1,
            registerVerify: 1,
            regVerifyCount: 1,
            addVerifyCount: 1,
            send: 1,
            r2Domain: '',
            secretKey: '',
            siteKey: '',
            regKey: 1,
            background: '',
            tgBotToken: '',
            tgChatId: '',
            tgBotStatus: 1,
            forwardEmail: '',
            forwardStatus: 1,
            ruleEmail: '',
            ruleType: 0,
            loginOpacity: 1.00,
            resendTokens: {},
            noticeTitle: '',
            noticeContent: '',
            noticeType: '',
            noticeDuration: 0,
            noticePosition: '',
            noticeOffset: 0,
            noticeWidth: 400,
            notice: 0,
            noRecipient: 1,
            loginDomain: 0,
            bucket: '',
            region: '',
            endpoint: '',
            s3AccessKey: '',
            s3SecretKey: '',
            forcePathStyle: 1,
            customDomain: '',
            tgMsgFrom: 'only-name',
            tgMsgTo: 'show',
            tgMsgText: 'hide',
            minEmailPrefix: 0,
            emailPrefixFilter: [],
            blackSubject: '',
            blackContent: '',
            blackFrom: '',
            aiCode: 1,
            aiCodeFilter: '',
            autoCleanDays: 0,
            subaddress: 1,
            webhookUrl: '',
            webhookStatus: 1,
            webhookSecret: '',
            webhookHeaders: '{}',
            domainList: [],
            hasR2: false,
        },
        lang: '',
    }),
    actions: {

    },
    persist: {
        pick: ['lang'],
    },
})
